# Generated by Django 3.2.11 on 2023-07-09 16:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CountryName', models.CharField(max_length=50)),
                ('NuclearTechnology', models.BooleanField()),
                ('NuclearRockets', models.IntegerField(validators=[django.core.validators.MaxValueValidator(20)])),
                ('Budget', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10000)])),
                ('Round', models.IntegerField(validators=[django.core.validators.MaxValueValidator(6)])),
                ('EnterCode', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=20)),
                ('Earnings', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5000)])),
            ],
            options={
                'verbose_name_plural': 'Сountry',
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=250)),
                ('live_level', models.IntegerField()),
                ('progress', models.IntegerField()),
                ('profit', models.IntegerField()),
                ('shield', models.BooleanField()),
                ('state', models.BooleanField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginPage.country')),
            ],
            options={
                'verbose_name_plural': 'City',
                'db_table': 'city',
            },
        ),
    ]
