# Generated by Django 3.2.11 on 2023-07-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='flag_photo',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
