# Generated by Django 3.2.11 on 2023-07-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginPage', '0002_country_flag_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CountryName', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Country_list',
                'db_table': 'country_list',
                'managed': False,
            },
        ),
    ]
