# Generated by Django 3.2.11 on 2023-07-11 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginPage', '0004_sanction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ecology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField(validators=[django.core.validators.MaxValueValidator(6)])),
                ('level', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name_plural': 'Ecology',
                'db_table': 'ecology',
                'managed': False,
            },
        ),
    ]
