# Generated by Django 3.2.11 on 2023-07-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forms_count', models.IntegerField()),
                ('forms_max', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Session',
                'db_table': 'session',
                'managed': False,
            },
        ),
    ]
