-- MySQL Script generated by MySQL Workbench
-- Sun Apr 30 14:47:18 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema worldDomination
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema worldDomination
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `worldDomination` DEFAULT CHARACTER SET utf8 ;
USE `worldDomination` ;

-- -----------------------------------------------------
-- Table `worldDomination`.`CountryInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worldDomination`.`CountryInfo` (
  `CountryName` VARCHAR(15) NOT NULL,
  `NuclearTechnology` ENUM("True", "False") NOT NULL,
  `NuclearRockets` INT NOT NULL,
  `Budget` INT NOT NULL,
  `Round` INT NOT NULL,
  `EnterCode` VARCHAR(8) NOT NULL,
  `Password` VARCHAR(10) NOT NULL,
  `Earnings` INT NOT NULL,
  PRIMARY KEY (`CountryName`),
  UNIQUE INDEX `EnterCode_UNIQUE` (`EnterCode` ASC) VISIBLE,
  UNIQUE INDEX `Password_UNIQUE` (`Password` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `worldDomination`.`CountryList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worldDomination`.`CountryList` (
  `CountryName` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`CountryName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `worldDomination`.`Sanctions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worldDomination`.`Sanctions` (
  `ID` INT NOT NULL,
  `CountryInfo_CountryName` VARCHAR(15) NOT NULL,
  `CountryList_CountryName` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`ID`, `CountryInfo_CountryName`, `CountryList_CountryName`),
  INDEX `fk_Sanctions_CountryInfo1_idx` (`CountryInfo_CountryName` ASC) VISIBLE,
  INDEX `fk_Sanctions_CountryList1_idx` (`CountryList_CountryName` ASC) VISIBLE,
  CONSTRAINT `fk_Sanctions_CountryInfo1`
    FOREIGN KEY (`CountryInfo_CountryName`)
    REFERENCES `worldDomination`.`CountryInfo` (`CountryName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sanctions_CountryList1`
    FOREIGN KEY (`CountryList_CountryName`)
    REFERENCES `worldDomination`.`CountryList` (`CountryName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `worldDomination`.`CityInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worldDomination`.`CityInfo` (
  `CityName` VARCHAR(20) NOT NULL,
  `PictureLink` VARCHAR(100) NOT NULL,
  `Growth` INT NOT NULL,
  `StandartOfLiving` INT NOT NULL,
  `Earnings` INT NOT NULL,
  `Shields` ENUM("None", "1", "2") NOT NULL,
  `CityType` ENUM("CapitalCity", "SecondCity", "ThirdCity", "LastCity") NOT NULL,
  `CountryName` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`CityName`, `CountryName`),
  UNIQUE INDEX `PictureLink_UNIQUE` (`PictureLink` ASC) VISIBLE,
  INDEX `fk_CityInfo_CountryInfo1_idx` (`CountryName` ASC) VISIBLE,
  CONSTRAINT `fk_CityInfo_CountryInfo1`
    FOREIGN KEY (`CountryName`)
    REFERENCES `worldDomination`.`CountryInfo` (`CountryName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `worldDomination`.`Admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worldDomination`.`Admins` (
  `ID` INT NOT NULL,
  `Login` VARCHAR(20) NOT NULL,
  `Password` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `AdminsLogin_UNIQUE` (`Login` ASC) VISIBLE,
  UNIQUE INDEX `Password_UNIQUE` (`Password` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `worldDomination`.`Presidents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worldDomination`.`Presidents` (
  `FormLogin` VARCHAR(10) NOT NULL,
  `FormPassword` VARCHAR(10) NOT NULL,
  `CountryInfo_CountryName` VARCHAR(15) NOT NULL,
  UNIQUE INDEX `FormLogin_UNIQUE` (`FormLogin` ASC) VISIBLE,
  UNIQUE INDEX `FormPassword_UNIQUE` (`FormPassword` ASC) VISIBLE,
  PRIMARY KEY (`CountryInfo_CountryName`),
  CONSTRAINT `fk_Presidents_CountryInfo1`
    FOREIGN KEY (`CountryInfo_CountryName`)
    REFERENCES `worldDomination`.`CountryInfo` (`CountryName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
